import { serve } from "https://deno.land/std@0.177.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { buildAuthorizeUrl, corsHeaders } from "../_shared/truelayer.ts";

/**
 * Creates a TrueLayer OAuth authorization URL.
 *
 * Body: { provider_id, provider_name, provider_logo?, provider_country? }
 * Auth: Supabase user session (Bearer token)
 *
 * Flow:
 *   1. Insert a pending-auth row keyed by a random UUID `state`.
 *   2. Build the TrueLayer authorize URL with that state and the
 *      HTTPS callback edge function as the redirect_uri.
 *   3. Return { url } — the app opens it in the system browser.
 *
 * When the user finishes at their bank, TrueLayer redirects to our
 * truelayer-callback function which looks up the state and completes
 * the connection.
 */
serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Authorization required" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL") ?? "";
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";

    const jwt = authHeader.replace("Bearer ", "");
    const admin = createClient(supabaseUrl, serviceKey);
    const { data: { user }, error: authError } = await admin.auth.getUser(jwt);

    if (authError || !user) {
      console.error("Auth error:", authError);
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const body = await req.json();
    const providerId = body.provider_id as string | undefined;
    const providerName = body.provider_name as string | undefined;
    const providerLogo = (body.provider_logo as string | undefined) ?? null;
    const providerCountry = (body.provider_country as string | undefined) ?? null;

    if (!providerId || !providerName) {
      return new Response(
        JSON.stringify({ error: "provider_id and provider_name required" }),
        {
          status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    // Insert pending auth (state PK is generated by default).
    const { data: pending, error: insertError } = await admin
      .from("truelayer_pending_auths")
      .insert({
        user_id: user.id,
        provider_id: providerId,
        provider_name: providerName,
        provider_logo: providerLogo,
        provider_country: providerCountry,
      })
      .select("state")
      .single();

    if (insertError || !pending) {
      console.error("Pending insert error:", insertError);
      return new Response(
        JSON.stringify({ error: "Failed to create pending auth" }),
        {
          status: 500,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    const redirectUri = `${supabaseUrl}/functions/v1/truelayer-callback`;
    const url = buildAuthorizeUrl({
      providerId,
      redirectUri,
      state: pending.state,
    });

    return new Response(JSON.stringify({ url, state: pending.state }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("create-auth-link error:", error);
    return new Response(
      JSON.stringify({ error: (error as Error).message ?? "Internal error" }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
