import { serve } from "https://deno.land/std@0.177.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { corsHeaders, createAuthSession } from "../_shared/enablebanking.ts";

/**
 * Creates an Enable Banking authorization URL.
 *
 * Body: { aspsp_name, aspsp_country, aspsp_logo? }
 * Auth: Supabase user session (Bearer token)
 *
 * Flow:
 *   1. Insert a pending-auth row keyed by a random UUID `state`.
 *   2. Call Enable Banking POST /auth to get the authorization URL.
 *   3. Return { url, state } — the app opens url in the system browser.
 */
serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(
        JSON.stringify({ error: "Authorization required" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL") ?? "";
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
    const admin = createClient(supabaseUrl, serviceKey);

    const jwt = authHeader.replace("Bearer ", "");
    const { data: { user }, error: authError } = await admin.auth.getUser(jwt);

    if (authError || !user) {
      return new Response(
        JSON.stringify({ error: "Unauthorized" }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const body = await req.json();
    const aspspName = body.aspsp_name as string | undefined;
    const aspspCountry = body.aspsp_country as string | undefined;
    const aspspLogo = (body.aspsp_logo as string | undefined) ?? null;

    if (!aspspName || !aspspCountry) {
      return new Response(
        JSON.stringify({ error: "aspsp_name and aspsp_country required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Insert pending auth row — state UUID is generated by DB default.
    const { data: pending, error: insertError } = await admin
      .from("truelayer_pending_auths")
      .insert({
        user_id: user.id,
        provider_id: `${aspspCountry.toLowerCase()}-${aspspName.toLowerCase().replace(/\s+/g, "-")}`,
        provider_name: aspspName,
        provider_logo: aspspLogo,
        provider_country: aspspCountry.toUpperCase(),
      })
      .select("state")
      .single();

    if (insertError || !pending) {
      console.error("Pending insert error:", insertError);
      return new Response(
        JSON.stringify({ error: "Failed to create pending auth" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const redirectUri = `${supabaseUrl}/functions/v1/enablebanking-callback`;
    const { url } = await createAuthSession({
      aspspName,
      aspspCountry,
      redirectUrl: redirectUri,
      state: pending.state,
    });

    return new Response(JSON.stringify({ url, state: pending.state }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("create-auth error:", error);
    return new Response(
      JSON.stringify({ error: (error as Error).message ?? "Internal error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
